import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,SAVE_KEY,shuffle} from '../src/engine.js';
import {CARDS,CHAPTERS,cardInfo} from '../src/data.js';
function fresh(){return new Game(null,()=>.42).init();}
function hand(g,ids){g.s.battle.hand=ids.map((id,i)=>({id,uid:100+i,upgraded:false}));g.s.battle.energy=3;}
test('opening encounter provides all party roles and affordable actions',()=>{const g=fresh();assert.equal(g.s.battle.hand.length,5);assert.equal(g.s.battle.energy,3);assert.equal(g.s.deck.length,14);assert.deepEqual(g.s.battle.hand.map(x=>x.id),['slash','spark','protect','bond','moon']);});
test('invalid and unaffordable plays do not mutate the battle',()=>{const g=fresh();const snapshot=JSON.stringify(g.s);assert.ok(g.play(-1).error);assert.equal(JSON.stringify(g.s),snapshot);g.s.battle.energy=0;const before=JSON.stringify(g.s);assert.ok(g.play(g.s.battle.hand[0].uid).error);assert.equal(JSON.stringify(g.s),before);});
test('different companions build a combo, with extra damage on the third card',()=>{const g=fresh();hand(g,['slash','spark','bash']);const enemy=g.s.battle.enemies[0];enemy.hp=100;g.play(100);g.play(101);const result=g.play(102);assert.equal(enemy.hp,68);assert.equal(g.s.battle.combo,0);assert.ok(result.effects.some(x=>x.type==='combo'));});
test('same owner restarts combo; end of turn clears it but retains qi and mana',()=>{const g=fresh();hand(g,['slash','slash','spark']);g.play(100);g.play(101);assert.equal(g.s.battle.combo,1);g.play(102);assert.equal(g.s.battle.combo,2);g.endTurn();assert.equal(g.s.battle.combo,0);assert.equal(g.s.battle.qi,2);assert.equal(g.s.battle.mana,1);assert.equal(g.s.battle.energy,3);assert.equal(g.s.battle.hand.length,5);});
test('resonance consumes both resources only if both thresholds are met',()=>{const g=fresh();hand(g,['moon']);g.s.battle.enemies[0].hp=100;g.s.battle.qi=2;g.s.battle.mana=2;g.play(100);assert.equal(g.s.battle.enemies[0].hp,66);assert.equal(g.s.battle.qi,0);assert.equal(g.s.battle.mana,0);const h=fresh();hand(h,['moon']);h.s.battle.qi=2;h.s.battle.mana=1;h.play(100);assert.equal(h.s.battle.qi,2);assert.equal(h.s.battle.mana,1);});
test('all-party block prevents forecast damage and expires next turn',()=>{const g=fresh();hand(g,['protect']);g.play(100);const before=g.s.party.map(h=>h.hp);const effects=g.endTurn();assert.deepEqual(g.s.party.map(h=>h.hp),before);assert.ok(effects.every(x=>x.amount===0));assert.ok(g.s.party.every(h=>h.block===0));});
test('weaken reduces incoming damage for its remaining duration',()=>{const g=fresh();const e=g.s.battle.enemies[0];e.weak=2;const hp=g.s.party[0].hp;g.endTurn();assert.equal(g.s.party[0].hp,hp-Math.floor(e.attack*.65));assert.equal(e.weak,1);});
test('dead enemy is skipped and a fallen heroine cannot play her cards',()=>{const g=fresh();g.s.battle.enemies[0].hp=0;g.s.party[0].hp=0;hand(g,['slash','spark']);assert.ok(g.play(100).error);const hp=g.s.battle.enemies[1].hp;g.play(101);assert.equal(g.s.battle.enemies[1].hp,hp-8);const effects=g.endTurn();assert.equal(effects.length,1);});
test('multi-hit and area damage respect defenses and grant one reward',()=>{const g=fresh();hand(g,['storm']);g.s.battle.enemies.forEach(e=>{e.hp=10;e.block=1;});g.play(100);assert.equal(g.s.phase,'reward');assert.equal(g.s.gold,110);assert.equal(g.s.battles,1);assert.equal(g.s.reward.length,3);assert.equal(g.claimReward('missing'),false);g.claimReward(g.s.reward[0]);assert.equal(g.s.deck.length,15);assert.equal(g.s.floor,1);assert.equal(g.s.phase,'map');});
test('reshuffling never loses cards',()=>{const g=fresh();g.s.battle.enemies.forEach(e=>e.attack=0);for(let turn=0;turn<14;turn++){g.endTurn();const b=g.s.battle;assert.equal(b.hand.length+b.draw.length+b.discard.length,14);assert.equal(new Set([...b.hand,...b.draw,...b.discard].map(x=>x.uid)).size,14);}});
test('rest revives, event decisions and shop mutations obey their phases',()=>{const g=fresh();assert.equal(g.buyCard('heal'),false);g.s.phase='map';g.s.floor=3;assert.equal(g.chooseNode('boss'),false);assert.equal(g.chooseNode('rest'),true);g.s.party[0].hp=0;g.rest();assert.equal(g.s.party[0].hp,26);assert.equal(g.s.floor,4);g.s.phase='shop';const gold=g.s.gold;assert.equal(g.buyCard('heal'),true);assert.equal(g.s.gold,gold-45);g.s.gold=0;assert.equal(g.buyCard('heal'),false);g.s.phase='event';g.event('prism');assert.ok(g.s.relics.includes('prism'));});
test('upgrading improves effects once; removing never makes an undersized deck',()=>{const g=fresh();const card=g.s.deck[0];assert.equal(g.upgrade(card.uid),true);assert.equal(cardInfo(card).damage,CARDS[card.id].damage+3);assert.equal(g.upgrade(card.uid),false);while(g.s.deck.length>8)assert.ok(g.remove(g.s.deck[0].uid));assert.equal(g.remove(g.s.deck[0].uid),false);});
test('save roundtrip preserves mid-turn state and rejects corrupt or unsupported data',()=>{const g=fresh();g.play(g.s.battle.hand[0].uid);const store=new Map();const storage={setItem:(k,v)=>store.set(k,v),getItem:k=>store.get(k)};assert.ok(g.save(storage));assert.deepEqual(Game.load(storage),g.s);const loaded=new Game(Game.load(storage));assert.equal(loaded.s.battle.energy,2);assert.equal(Game.load({getItem:()=>'{bad'}),null);assert.equal(Game.load({getItem:()=>JSON.stringify({...g.s,chapter:9})}),null);assert.equal(Game.load({getItem:()=>JSON.stringify({...g.s,party:[]})}),null);assert.equal(g.save({setItem:()=>{throw Error();}}),false);assert.ok(store.has(SAVE_KEY));});
test('all four bosses lead to the ending, without leaking a previous boss phase',()=>{const g=fresh();for(let c=0;c<CHAPTERS.length;c++){g.s.floor=5;g.s.phase='map';assert.ok(g.chooseNode('boss'));assert.equal(g.s.battle.enemies[0].id,CHAPTERS[c].boss);g.s.battle.enemies[0].hp=1;hand(g,['slash']);g.play(100);assert.equal(g.s.phase,'reward');g.claimReward(null);assert.equal(g.s.phase,'chapter');g.nextChapter();assert.equal(g.s.phase,c<3?'map':'ending');if(c<3){assert.equal(g.s.floor,0);assert.equal(g.s.battle,null);}}});
test('total defeat terminates the battle and prevents further card actions',()=>{const g=fresh();g.s.party.forEach(h=>h.hp=1);g.s.battle.enemies.push({...g.s.battle.enemies[0],uid:2,target:2});g.endTurn();assert.equal(g.s.phase,'defeat');assert.ok(g.play(1).error);assert.deepEqual(g.endTurn(),[]);});
test('shuffle does not mutate the source',()=>{const original=[1,2,3,4];assert.deepEqual(shuffle(original,()=>0).sort(),original);assert.deepEqual(original,[1,2,3,4]);});
test('boss area attacks hit all living allies and honor each shield',()=>{const g=fresh();g.startBattle('boss');g.s.battle.turn=3;g.s.party.forEach(h=>h.block=4);const before=g.s.party.map(h=>h.hp);assert.equal(g.intent(g.s.battle.enemies[0]).type,'sweep');const effects=g.endTurn();assert.equal(effects.length,3);assert.deepEqual(g.s.party.map(h=>h.hp),before.map(h=>h-5));});
test('chapter three always encounters the cult leader on the fifth floor',()=>{const g=fresh();g.s.chapter=2;g.s.floor=4;g.s.phase='map';g.chooseNode('battle');assert.equal(g.s.battle.enemies[0].id,'cult');});
test('import rejects invalid targets, prototype card names, and duplicate deck ids',()=>{const g=fresh();const bad=change=>{const copy=structuredClone(g.s);change(copy);return Game.load({getItem:()=>JSON.stringify(copy)});};assert.equal(bad(s=>s.battle.enemies[0].target=7),null);assert.equal(bad(s=>s.deck[0].id='toString'),null);assert.equal(bad(s=>s.deck[1].uid=s.deck[0].uid),null);});
test('import normalizes display names and rejects invalid retained ending battles',()=>{const g=fresh();g.s.battle.enemies[0].name='<img src=x onerror=alert(1)>';const restored=Game.load({getItem:()=>JSON.stringify(g.s)});assert.equal(restored.battle.enemies[0].name,'그림자 늑대');g.s.phase='ending';g.s.battle={};assert.equal(Game.load({getItem:()=>JSON.stringify(g.s)}),null);});
