import {Game,SAVE_KEY} from './engine.js';
import {HEROES,CARDS,RELICS,CHAPTERS,EVENTS,cardInfo} from './data.js';
import {Scene,portrait,cardArt,AudioFX} from './art.js';
const $=s=>document.querySelector(s),escape=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
let storage;try{storage=window.localStorage;}catch{storage={getItem:()=>null,setItem:()=>{throw Error('storage');},removeItem:()=>{}};}
let game=new Game(Game.load(storage)).init(),scene=null,busy=false,modalName=null,tutorial=!game.s.introSeen,saveWarning=false;const audio=new AudioFX();
const glyph={battle:'⚔',elite:'♜',boss:'♛',rest:'♧',event:'◇',shop:'▱'},nodeNames={battle:'전투',elite:'정예 전투',boss:'우두머리',rest:'야영지',event:'이야기',shop:'떠돌이 상인'};
const phaseLabel={battle:'전투 진행 중',map:'다음 길을 선택하세요',reward:'전투 승리',rest:'잠깐의 쉼',event:'뜻밖의 만남',shop:'길 위의 상인',chapter:'새로운 경계',ending:'원정 완료',defeat:'원정 종료'};
function save(){if(!game.save(storage)&&!saveWarning){saveWarning=true;toast('이 브라우저에서는 자동 저장이 제한됩니다. 창을 닫으면 진행이 사라질 수 있습니다.');}}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3200);}
function cardText(instance){const c=cardInfo(instance);let text=c.text;if(instance.upgraded){const b=CARDS[instance.id];if(b.damage)text=text.replace(new RegExp(`피해 ${b.damage}(?!\\d)`),`피해 ${c.damage}`);if(b.block)text=text.replace(`방어 ${b.block}`,`방어 ${c.block}`);if(b.heal)text=text.replace(`체력 ${b.heal}`,`체력 ${c.heal}`);}return text;}
function cardMarkup(instance,action='play',index=0){const c=cardInfo(instance),hero=HEROES.find(h=>h.id===c.owner),error=action==='play'?game.canPlay(instance):'';return `<button class="game-card ${c.type==='연계'?'rare':''} ${instance.upgraded?'upgraded':''} ${error?'unplayable':''}" style="--card-color:${hero.color};--card-index:${index}" data-action="${action}" data-uid="${instance.uid}" data-card="${instance.id}" ${action==='play'&&error?'aria-disabled="true"':''} aria-label="${escape(c.name)}: 행동력 ${c.cost}. ${escape(cardText(instance))}" title="${escape(error||'클릭하여 사용')}"><div class="card-heading"><span class="card-cost">${c.cost}</span><span class="card-name">${c.name}</span><span class="card-rune">${c.type==='연계'?'☾':'✧'}</span></div><canvas class="card-art" data-icon="${c.icon}" data-owner="${c.owner}"></canvas><div class="card-type">${hero.name} <span>·</span> ${c.type}${c.rarity?' · '+c.rarity:''}</div><p>${cardText(instance)}</p><div class="card-bottom"><span>${hero.role}</span><span>✦</span><span>${action==='play'?index+1:instance.upgraded?'강화됨':'월영'}</span></div></button>`;}
function drawSmallArt(){document.querySelectorAll('canvas[data-hero]').forEach(cv=>portrait(cv,cv.dataset.hero));document.querySelectorAll('canvas.card-art').forEach(cv=>cardArt(cv,cv.dataset.icon,cv.dataset.owner));}
function render(){
 scene?.stop();const s=game.s,b=s.battle,c=CHAPTERS[s.chapter],fighting=s.phase==='battle';
 $('#app').innerHTML=`<div class="shell"><header class="header"><a class="brand" href="#" data-action="home" aria-label="월영 게임으로"><span class="brand-moon">☾</span><span class="brand-title">월영<small>MOONVEIL</small></span><span class="brand-divider"></span><span class="brand-subtitle">경계를 넘는 검</span></a><nav aria-label="게임 메뉴"><button class="nav-item active" data-action="home"><span>⚔</span> 원정</button><button class="nav-item" data-action="map"><span>⌘</span> 여정 지도</button><button class="nav-item" data-action="deck"><span>▤</span> 나의 덱 <small>${s.deck.length}</small></button><button class="nav-item" data-action="story"><span>◇</span> 이야기</button></nav><div class="header-right"><span class="save-status"><i></i> 자동 저장</span><button class="icon-button" data-action="audio" title="효과음 켜기/끄기" aria-label="효과음 ${audio.enabled?'끄기':'켜기'}">${audio.enabled?'♫':'♩'}</button><button class="icon-button" data-action="settings" title="도움말과 설정" aria-label="도움말과 설정">⚙</button></div></header>
 <div class="chapterbar"><div><span class="eyebrow">CHAPTER 0${s.chapter+1}</span><span class="chapter-name">${c.title}</span><span class="chapter-world">${c.world}</span></div><div class="chapter-progress">${Array.from({length:6},(_,i)=>`<span class="${i<s.floor?'done':i===s.floor?'current':''}">${i===5?'♛':'◆'}</span>${i<5?'<i></i>':''}`).join('')}<small>${s.floor+1} / 6</small></div><div class="gold"><span>◈</span> ${s.gold}<small>금</small></div></div>
 <div class="game-layout"><aside class="party-panel"><div class="panel-heading"><span>나의 동료</span><small>PARTY OF 3</small></div><p class="aside-caption">함께라서, 더 강해지는 검.</p><div class="party-list">${s.party.map((h,i)=>{const hero=HEROES[i];return `<div class="hero-card ${h.hp<=0?'fallen':''}" style="--hero-color:${hero.color}"><div class="hero-upper"><canvas data-hero="${hero.id}" aria-hidden="true"></canvas><div><div class="hero-name">${hero.name}<span>${hero.role}</span></div><small>${hero.title}</small></div><span class="hero-order">0${i+1}</span></div><div class="hero-health"><span>♥ ${Math.ceil(h.hp)}<small> / ${h.maxHp}</small></span>${h.block>0?`<span class="block-value">⛨ ${h.block}</span>`:h.hp<=0?'<small>전투 불능</small>':'<small>체력</small>'}</div><div class="health-track"><div style="width:${h.hp/h.maxHp*100}%"></div></div><div class="hero-status">${h.hp<=0?'야영지에서 다시 일어납니다.':fighting&&b?.lastOwner===hero.id?'✦ 연계의 흐름을 이어 가세요':hero.id==='seol'?'기 · 무공의 흐름':hero.id==='lyra'?'마나 · 별의 흐름':'수호 · 동료의 버팀목'}</div></div>`;}).join('')}</div><div class="relic-heading"><span>여정의 유물</span><small>${s.relics.length} / 5</small></div><div class="relics">${s.relics.map(id=>`<button data-action="relic" data-id="${id}" title="${RELICS[id].name}: ${RELICS[id].text}" aria-label="${RELICS[id].name}">${RELICS[id].icon}</button>`).join('')}</div><div class="party-quote"><span>“</span><p>세계가 달라도,<br>우리의 약속은 하나니까.</p><small>— 설아</small></div><button class="help-button" data-action="guide"><span>?</span> 전투 가이드 <small>↗</small></button></aside>
 <main><div class="battle-heading"><div><span class="eyebrow">${s.chapter===0?'THE MOONLIT WOODS':s.chapter===1?'THE ASHEN CITADEL':s.chapter===2?'THE FALLEN SECT':'THE WORLD BETWEEN'}</span><h1>${c.subtitle}<span>·</span><small>${b?.type==='boss'?c.bossName:b?.type==='elite'?'정예 조우':'그림자와의 조우'}</small></h1></div><div class="battle-status"><i></i>${phaseLabel[s.phase]}</div></div>
 <section class="battle-scene" aria-label="픽셀 아트 전투 장면"><canvas id="scene" aria-label="세 여성 동료가 달빛 숲에서 적과 마주합니다."></canvas><div class="scene-vignette"></div><div class="scene-location"><span>◇</span> ${c.subtitle}<small>구역 ${s.floor+1}</small></div><span class="scene-turn">${fighting?`TURN ${String(b.turn).padStart(2,'0')}`:'MOONVEIL'}</span>${b?b.enemies.map((e,i)=>{const intent=game.intent(e),target=HEROES[intent.target],damage=Math.floor(intent.amount*(e.weak>0&&intent.type!=='guard'?.65:1));return `<button class="enemy-info ${e.hp<=0?'dead':''} ${b.selected===e.uid?'selected':''}" style="left:${b.enemies.length===1?76.6:67.7+i*18.2}%" data-action="target" data-uid="${e.uid}" ${e.hp<=0||!fighting?'disabled':''} aria-label="${e.name}, 체력 ${e.hp}. 다음 ${intent.label} ${damage}. 공격 대상 선택"><div class="enemy-intent">${intent.type==='guard'?'⛨':'⚔'} <b>${damage}</b><span>${intent.type==='guard'?'방어':intent.type==='sweep'?'전원 공격':target.name+' 공격'}${e.weak>0?' · 약화':''}</span></div><div class="enemy-name">${e.name}</div><div class="enemy-healthbar"><i style="width:${Math.max(0,e.hp/e.maxHp*100)}%"></i></div><small>${Math.ceil(e.hp)} / ${e.maxHp}${e.block?' · ⛨ '+e.block:''}</small>${b.selected===e.uid&&e.hp>0?'<div class="target-label">⌖ 선택한 대상</div>':''}</button>`;}).join(''):''}<div class="character-labels"><span>설아</span><span>리라</span><span>아리아</span></div><div class="scene-bottom"><span class="weather">✧ 달빛이 흐르는 밤</span><span>${fighting?'적을 선택하고 카드를 사용하세요.':'이야기는 당신의 선택으로 이어집니다.'}</span></div><div id="fx-caption" aria-live="polite"></div></section>
 <div class="combat-toolbar"><div class="energy-wrap"><div class="energy-orb">${fighting?b.energy:'—'}<small>/ 3</small></div><div><strong>행동력</strong><small>매 턴 충전</small></div></div><span class="toolbar-divider"></span><div class="resource qi"><span>◉</span><div><strong>기 <b>${b?.qi||0}</b><small>/ 6</small></strong><span>무공의 흐름</span></div></div><div class="resource mana"><span>✧</span><div><strong>마나 <b>${b?.mana||0}</b><small>/ 6</small></strong><span>별의 흐름</span></div></div><div class="combo-meter"><div><strong>동료 연계</strong><small>${b?.combo||0} / 3</small></div><div class="combo-pips">${[1,2,3].map(i=>`<i class="${(b?.combo||0)>=i?'filled':''}"></i>`).join('')}</div></div><button class="end-turn" data-action="${fighting?'endturn':'continue'}" ${busy?'disabled':''}>${fighting?'턴 종료':'여정 계속'} <span>→</span><small>${fighting?'SPACE':'선택하기'}</small></button></div>
 <section class="hand-section"><div class="hand-heading"><span>${fighting?'손에 든 카드':'우리의 여정'} <small>${fighting?(b.hand.length+'장'):'네 개의 세계, 하나의 약속'}</small></span><span>${fighting?'카드를 클릭하여 사용 · 숫자 1–9':'카드의 선택이 이야기를 만듭니다.'}</span></div>${fighting?`<div class="hand">${b.hand.map((x,i)=>cardMarkup(x,'play',i)).join('')||'<div class="empty-hand">손패를 모두 사용했습니다. 턴을 종료하면 새 카드 5장을 뽑습니다.</div>'}</div>`:`<div class="journey-prompt"><span>☾</span><div><h2>${phaseLabel[s.phase]}</h2><p>${s.phase==='ending'?'세계를 지킨 것은 검 하나가 아니라, 서로를 놓지 않은 마음이었다.':'다음 선택이 세 사람의 운명을 이어 갑니다.'}</p></div><button class="outline-button" data-action="continue">${s.phase==='ending'?'에필로그 읽기':'계속하기'} →</button></div>`}</section>
 <div class="battle-footer"><button data-action="pile" data-pile="draw"><span>▱</span> 뽑기 더미 <b>${b?.draw.length||0}</b></button><span class="footer-message">${tutorial&&fighting?'✦ 서로 다른 동료의 카드를 3번 잇면, 연계가 발동합니다.':'기와 마나가 만나는 순간, 새로운 검이 깨어난다.'}${tutorial&&fighting?'<button data-action="dismiss" aria-label="팁 닫기">×</button>':''}</span><button data-action="pile" data-pile="discard">버린 더미 <b>${b?.discard.length||0}</b> <span>▤</span></button></div>
 </main></div><footer class="site-footer"><span>MOONVEIL <i>✦</i> 경계를 넘는 검</span><span>작은 선택들이 만드는, 우리만의 서사.</span><span>PIXEL PARTY DECKBUILDER <b>v1.0</b></span></footer></div>`;
 drawSmallArt();const enemies=b?.enemies||[];scene=new Scene($('#scene'),s.chapter,s.party,enemies);save();
}
function modal(title,eyebrow,body,wide=false){modalName=eyebrow;$('#overlay-root').innerHTML=`<div class="modal-backdrop"><section class="modal ${wide?'wide':''}" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-top"><div><span class="eyebrow">${eyebrow}</span><h2 id="modal-title">${title}</h2></div><button class="modal-close" data-action="close" aria-label="닫기">×</button></div>${body}</section></div>`;drawSmallArt();$('.modal-close').focus();}
function close(){modalName=null;$('#overlay-root').innerHTML='';$('.nav-item')?.focus();}
function mapModal(){const s=game.s;const routes=[['battle','battle'],['event','shop'],['elite','battle'],['rest','event'],['battle','elite'],['boss']];modal('달빛을 따라, 다음 여정으로','JOURNEY MAP',`<p class="modal-lead">제 ${s.chapter+1}장 · ${CHAPTERS[s.chapter].title} <span>체력과 덱을 생각하며 다음 길을 고르세요.</span></p><div class="map-path">${routes.map((row,f)=>`<div class="map-floor ${f===s.floor?'now':f<s.floor?'past':'future'}"><span class="floor-number">${String(f+1).padStart(2,'0')}</span><div class="map-nodes">${row.map(type=>`<button class="map-node ${type}" data-action="node" data-type="${type}" ${s.phase!=='map'||f!==s.floor?'disabled':''}><span>${f<s.floor?'✓':glyph[type]}</span><div><strong>${nodeNames[type]}</strong><small>${type==='battle'?'카드 · 30금':type==='elite'?'위험 증가 · 유물':type==='boss'?CHAPTERS[s.chapter].bossName:type==='event'?'뜻밖의 인연':type==='shop'?'카드 구입 · 정리':'회복 · 카드 강화'}</small></div>${f===s.floor&&s.phase==='map'?'<b>→</b>':''}</button>`).join('')}</div>${f===s.floor?`<span class="you-here">${s.phase==='map'?'다음 선택':'현재 위치'}</span>`:''}</div>`).join('')}</div><div class="modal-note">${s.phase==='battle'?'현재 전투를 마치면 다음 길을 선택할 수 있습니다.':'우두머리를 쓰러뜨리면 다음 장으로 넘어갑니다.'} · 진행 상황은 자동 저장됩니다.</div>`,true);}
function deckModal(mode='deck',context=null){let cards=game.s.deck;if(mode==='upgrade')cards=cards.filter(c=>!c.upgraded);if(mode==='draw'||mode==='discard')cards=game.s.battle?.[mode]||[];if(mode==='draw')cards=[...cards].sort((a,b)=>a.id.localeCompare(b.id));const title=mode==='upgrade'?'검에 새로운 흐름을 새기다':mode==='remove'?'놓아야 할 검식을 고르세요':mode==='draw'?'뽑기 더미':mode==='discard'?'버린 더미':'나의 덱';modal(title,'YOUR COLLECTION',`<p class="modal-lead">${mode==='upgrade'?'카드 1장을 골라 피해, 방어 또는 회복량을 3 올립니다. 자원·뽑기 전용 카드는 변화가 없습니다.':mode==='remove'?'카드 한 장을 영구히 제거합니다. 덱은 최소 8장을 유지합니다.':mode==='draw'?'표시 순서는 이름순입니다. 실제 뽑는 순서는 공개되지 않습니다.':mode==='discard'?'뽑기 더미가 비면 이 카드들을 섞어 다시 뽑습니다.':`총 ${cards.length}장 · 검객, 마법사, 수호자의 흐름을 함께 설계하세요.`}</p><div class="collection-grid">${cards.map((x,i)=>cardMarkup(x,mode==='upgrade'?'upgrade':mode==='remove'?'remove':'inspect',i)).join('')||'<p class="empty-hand">카드가 없습니다.</p>'}</div>${context?`<input type="hidden" id="deck-context" value="${context}">`:''}`,true);}
function rewardModal(){const b=game.s.battle;modal('승리의 끝, 새로운 가능성','BATTLE REWARDS',`<div class="reward-summary"><span>✦ 전투 승리</span><span>◈ ${b.type==='boss'?85:b.type==='elite'?55:30}금 획득</span>${b.type!=='battle'?'<span>◇ 새로운 유물 획득</span>':''}</div><p class="modal-lead">덱에 추가할 카드 1장을 선택하세요. <span>필요 없는 보상은 건너뛸 수 있습니다.</span></p><div class="reward-cards">${game.s.reward.map((id,i)=>cardMarkup({id,uid:0,upgraded:false},'reward',i)).join('')}</div><button class="text-button centered" data-action="skipreward">카드 보상 건너뛰기 →</button>`);}
function restModal(){modal('잠시, 검을 내려놓고','A MOMENT OF REST',`<div class="event-art">♧</div><p class="event-text">아리아는 작은 불을 피우고 리라는 별자리를 읽는다.<br>설아는 검 대신 따뜻한 찻잔을 쥔다.<br>오늘은 모두가 무사히 돌아왔다.</p><div class="event-choices"><button data-action="rest"><strong>따뜻한 불가에서 쉬기</strong><small>모든 동료 체력 26 회복 · 쓰러진 동료 부활</small><span>→</span></button><button data-action="campupgrade"><strong>달빛 아래 수련하기</strong><small>카드 1장 강화 · 회복 없이 여정 계속</small><span>→</span></button></div>`);}
function eventModal(){const e=EVENTS[game.s.chapter];modal(e.title,'A CHANCE ENCOUNTER',`<div class="event-art">◇</div><h3 class="event-subtitle">${e.subtitle}</h3><p class="event-text">${e.text}</p><div class="event-choices">${e.choices.map(ch=>`<button data-action="event" data-effect="${ch.effect}"><strong>${ch.label}</strong><small>${ch.detail}</small><span>→</span></button>`).join('')}</div>`);}
function shopModal(){const offers=[['lotus','storm','heal'],['nova','fortress','focus'],['frost','heal','lotus'],['nova','fortress','flash']][game.s.chapter];modal('길 위의 작은 거래','THE WANDERING MERCHANT',`<p class="modal-lead">“내일의 자신에게 필요한 것을 고르세요.” <span>보유 금화 <b>◈ ${game.s.gold}</b></span></p><div class="reward-cards">${offers.map((id,i)=>`<div class="shop-offer">${cardMarkup({id,uid:0,upgraded:false},'inspect',i)}<button class="outline-button" data-action="buy" data-card="${id}" ${game.s.gold<45?'disabled':''}>◈ 45금 · 구입</button></div>`).join('')}</div><div class="shop-bottom"><button class="outline-button" data-action="shopremove" ${game.s.gold<35||game.s.deck.length<=8?'disabled':''}>카드 제거 · 35금</button><button class="primary-button" data-action="leave">여정 계속 →</button></div>`);}
function chapterModal(){const c=CHAPTERS[game.s.chapter];modal(c.title,'CHAPTER COMPLETE',`<div class="event-art">☾</div><p class="event-text">${c.outro}</p>${game.s.chapter<3?`<div class="next-chapter"><span>다음 장 · 0${game.s.chapter+2}</span><h3>${CHAPTERS[game.s.chapter+1].title}</h3><p>${CHAPTERS[game.s.chapter+1].intro}</p></div>`:'<div class="next-chapter"><h3>두 세계를 잇는, 하나의 약속.</h3><p>마지막 여정이 끝났습니다. 세 사람의 이야기는 계속됩니다.</p></div>'}<button class="primary-button centered" data-action="nextchapter">${game.s.chapter<3?'다음 세계로 · 모두 체력 25 회복':'에필로그로'} →</button>`);}
function endingModal(){modal('우리가 돌아갈 곳','THE END · A NEW BEGINNING',`<div class="event-art">☾</div><p class="event-text">${CHAPTERS[3].outro}</p><div class="ending-stats"><span>완료한 전투 <b>${game.s.battles}</b></span><span>모은 카드 <b>${game.s.deck.length}</b></span><span>함께한 동료 <b>3</b></span></div><p class="modal-note">첫 원정 완료. 다른 경로와 카드 조합으로 새 원정을 시작할 수 있습니다.</p><button class="primary-button centered" data-action="newconfirm">새로운 원정 →</button>`);}
function defeatModal(){modal('오늘의 밤은 여기까지','THE JOURNEY WILL CONTINUE',`<div class="event-art">☾</div><p class="event-text">모든 동료가 쓰러졌습니다.<br>전투 전 적의 행동을 살피고, 방어 카드를 섞어 사용해 보세요.<br>지나온 길에서 배운 것은 사라지지 않습니다.</p><div class="ending-stats"><span>도달한 장 <b>${game.s.chapter+1}</b></span><span>완료한 전투 <b>${game.s.battles}</b></span></div><button class="primary-button centered" data-action="newconfirm">다시 시작하기 →</button>`);}
function phaseModal(){const phase=game.s.phase;if(phase==='map')mapModal();else if(phase==='reward')rewardModal();else if(phase==='rest')restModal();else if(phase==='event')eventModal();else if(phase==='shop')shopModal();else if(phase==='chapter')chapterModal();else if(phase==='ending')endingModal();else if(phase==='defeat')defeatModal();else close();}
function storyModal(){modal('달빛 아래 쓰인 이야기','CHRONICLES OF MOONVEIL',`<p class="modal-lead">이야기의 시작과, 지금까지 걸어온 길.</p><article class="story-entry"><span>프롤로그 · 청운문의 밤</span><h3>모든 것은 들리지 말아야 할 말에서 시작됐다.</h3><p>차를 나르던 설아는 장문 연화가 마교의 사절과 거래하는 장면을 목격한다. “월석만 넘기면 무림은 당신의 것이오.” 연화는 누구도 믿지 않을 말단 제자를 죽이려 한다. 벼랑 끝에서 설아가 움켜쥔 것은 어머니가 남긴 금 간 월석이었다. 죽음 대신, 낯선 세계의 달이 떠올랐다.</p></article>${CHAPTERS.map((c,i)=>`<article class="story-entry ${i>game.s.chapter?'locked-story':''}"><span>제 ${i+1}장 · ${c.world}</span><h3>${c.title}</h3><p>${i>game.s.chapter?'이 세계의 이야기는 앞으로의 여정에서 열립니다.':c.intro}</p>${i<game.s.chapter||['chapter','ending'].includes(game.s.phase)&&i===game.s.chapter?`<p class="story-resolution">${c.outro}</p>`:''}</article>`).join('')}<div class="story-heroes">${HEROES.map(h=>`<article><canvas data-hero="${h.id}"></canvas><h3>${h.name} · ${h.role}</h3><p>${h.lore}</p></article>`).join('')}</div>`,true);}
function guideModal(){modal('검과 별의 흐름을 잇는 법','BATTLE GUIDE',`<div class="guide-grid"><article><b>01</b><h3>선택하고, 사용하세요</h3><p>적을 클릭해 공격 대상을 선택한 뒤 카드를 클릭합니다. 카드 왼쪽 위의 숫자만큼 공용 행동력을 사용합니다. 매 턴 행동력 3, 새 카드 5장으로 시작합니다.</p></article><article><b>02</b><h3>예고된 공격을 막으세요</h3><p>적 위의 숫자와 이름은 다음 턴의 피해와 공격 대상입니다. 방어는 동료 모두에게 적용되고, 적의 행동을 막은 뒤 다음 턴에 사라집니다. 체력 0인 동료의 카드는 사용할 수 없습니다.</p></article><article><b>03</b><h3>기와 마나를 모으세요</h3><p>무공 카드는 기, 마법 카드는 마나를 쌓습니다. 두 자원은 전투 안에서 턴이 지나도 유지되며 최대 6입니다. 공명 카드는 조건이 갖춰지면 자원을 소비해 강해집니다.</p></article><article><b>04</b><h3>동료에게 흐름을 넘기세요</h3><p>서로 다른 동료의 카드를 이어서 3번 사용하면 마지막 카드의 피해 또는 방어가 5 증가합니다. 같은 동료를 연달아 사용하면 1부터 다시 쌓이고, 턴 종료 시 초기화됩니다.</p></article><article><b>05</b><h3>덱을 다듬으세요</h3><p>승리하면 금화와 카드 선택 보상을 얻습니다. 정예와 우두머리는 유물도 줍니다. 보상을 건너뛰고 상인에게 카드를 제거하면 필요한 카드를 더 자주 뽑을 수 있습니다.</p></article><article><b>06</b><h3>다시 일어서는 여정</h3><p>야영과 회복 이벤트에서 쓰러진 동료도 부활합니다. 장을 넘으면 모두 체력 25를 회복합니다. 모든 동료가 쓰러지면 처음부터 새 원정을 시작합니다.</p></article></div><div class="shortcut-note"><kbd>1</kbd>–<kbd>9</kbd> 카드 사용 <kbd>SPACE</kbd> 턴 종료 <kbd>M</kbd> 지도 <kbd>D</kbd> 덱 <kbd>ESC</kbd> 창 닫기</div>`,true);}
function settingsModal(){modal('나만의 여정','SETTINGS & HELP',`<div class="settings-list"><button data-action="audio"><span>효과음</span><b>${audio.enabled?'켜짐 ♫':'꺼짐 ♩'}</b></button><button data-action="guide"><span>전투 규칙과 조작</span><b>가이드 →</b></button><button data-action="export"><span>저장 데이터 내보내기</span><b>JSON ↓</b></button><label class="import-label"><span>저장 데이터 불러오기</span><b>JSON ↑</b><input type="file" id="import-save" accept="application/json,.json"></label><button class="danger-option" data-action="newconfirm"><span>새 원정 시작</span><b>진행 초기화 →</b></button></div><p class="modal-note">진행은 현재 브라우저에 자동 저장됩니다. GitHub Pages 등 다른 주소에서는 별도의 저장 공간을 사용합니다. 내보내기로 진행을 옮길 수 있습니다.</p>`);}
function resetConfirm(){modal('새로운 달 아래에서','NEW EXPEDITION',`<p class="event-text">현재 원정의 카드, 체력, 여정이 초기화됩니다.<br>설정에서 저장 파일을 내보내면 나중에 이어갈 수 있습니다.</p><div class="confirm-buttons"><button class="outline-button" data-action="settings">돌아가기</button><button class="primary-button" data-action="reset">새 원정 시작</button></div>`);}
function afterMutation(){render();phaseModal();}
async function animate(effects){for(const e of effects)scene?.burst(e);const special=effects.find(e=>e.type==='combo'||e.type==='resonate');if(special){$('#fx-caption').textContent=special.text;$('#fx-caption').className='visible';audio.play('combo');}else audio.play(effects.some(e=>e.type==='enemy')?'enemy':effects.some(e=>e.type==='attack')?'attack':'block');await new Promise(r=>setTimeout(r,matchMedia('(prefers-reduced-motion: reduce)').matches?180:650));$('#fx-caption')?.classList.remove('visible');}
async function handle(action,el){if(busy&&['play','endturn','reset','node','reward','skipreward','import'].includes(action))return;
 if(action==='play'){const result=game.play(Number(el.dataset.uid));if(result.error){toast(result.error);return;}busy=true;render();await animate(result.effects);busy=false;render();if(game.s.phase!=='battle')phaseModal();return;}
 if(action==='endturn'){if(game.s.phase!=='battle')return;busy=true;const effects=game.endTurn();render();await animate(effects);busy=false;render();if(game.s.phase!=='battle')phaseModal();return;}
 if(action==='target'){if(game.s.phase!=='battle')return;const enemy=game.s.battle.enemies.find(e=>e.uid===Number(el.dataset.uid)&&e.hp>0);if(enemy){game.s.battle.selected=enemy.uid;render();}return;}
 if(action==='close')return close();
 if(action==='home'){close();return;}
 if(action==='map')return mapModal();
 if(action==='deck')return deckModal();
 if(action==='story')return storyModal();
 if(action==='guide')return guideModal();
 if(action==='settings')return settingsModal();
 if(action==='audio'){audio.enabled=!audio.enabled;const settings=modalName==='SETTINGS & HELP';render();if(settings)settingsModal();toast(`효과음 ${audio.enabled?'켜짐':'꺼짐'}`);return;}
 if(action==='continue')return phaseModal();
 if(action==='node'){if(game.chooseNode(el.dataset.type))afterMutation();return;}
 if(action==='reward'||action==='skipreward'){if(game.claimReward(action==='reward'?el.dataset.card:null))afterMutation();return;}
 if(action==='rest'){game.rest();afterMutation();return;}
 if(action==='campupgrade')return deckModal('upgrade','camp');
 if(action==='upgrade'||action==='remove'){
 const context=$('#deck-context')?.value;
 if(context==='shop'&&(game.s.gold<35||game.s.phase!=='shop')){toast('금화가 부족합니다.');return;}
 if((context==='camp'&&game.s.phase!=='rest')||(context==='event'&&game.s.phase!=='event'))return;
 const instance=game.s.deck.find(x=>x.uid===Number(el.dataset.uid));if(action==='upgrade'&&instance){const c=CARDS[instance.id];if(!c.damage&&!c.block&&!c.heal){toast('이 카드는 피해·방어·회복 효과가 없어 강화할 수 없습니다.');return;}}
 const ok=action==='upgrade'?game.upgrade(Number(el.dataset.uid)):game.remove(Number(el.dataset.uid));if(!ok){toast(action==='remove'?'덱은 최소 8장을 유지해야 합니다.':'이미 강화한 카드입니다.');return;}
 if(context==='shop'){game.s.gold-=35;render();shopModal();}else{game.finishNode();afterMutation();}toast(action==='upgrade'?'카드가 강화되었습니다.':'카드를 덱에서 제거했습니다.');return;
 }
 if(action==='event'){const effect=el.dataset.effect;if(effect==='upgrade'||effect==='remove')return deckModal(effect,'event');if(game.event(effect))afterMutation();return;}
 if(action==='buy'){if(game.buyCard(el.dataset.card)){render();shopModal();toast('새 카드를 덱에 추가했습니다.');}else toast('금화가 부족합니다.');return;}
 if(action==='shopremove')return deckModal('remove','shop');
 if(action==='leave'){if(game.s.phase==='shop'){game.finishNode();afterMutation();}return;}
 if(action==='nextchapter'){game.nextChapter();afterMutation();return;}
 if(action==='newconfirm')return resetConfirm();
 if(action==='reset'){game=new Game().init();tutorial=true;close();render();toast('새로운 원정이 시작되었습니다.');return;}
 if(action==='dismiss'){tutorial=false;game.s.introSeen=true;render();return;}
 if(action==='relic'){const r=RELICS[el.dataset.id];toast(`${r.name} — ${r.text}`);return;}
 if(action==='pile')return deckModal(el.dataset.pile);
 if(action==='inspect'){toast(`${cardInfo({id:el.dataset.card,upgraded:el.classList.contains('upgraded')}).name} — ${CARDS[el.dataset.card].flavor}`);return;}
 if(action==='export'){const blob=new Blob([JSON.stringify(game.s,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='moonveil-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('저장 파일을 내보냈습니다.');return;}
}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;e.preventDefault();handle(el.dataset.action,el);});
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;if(e.key==='Escape')return close();if(modalName||busy)return;if(e.target.closest('button,a')&&(e.key===' '||e.key==='Enter'))return;const key=e.key.toLowerCase();if(key==='m'){mapModal();return;}if(key==='d'){deckModal();return;}if(e.code==='Space'&&game.s.phase==='battle'){e.preventDefault();handle('endturn',$('[data-action="endturn"]'));return;}if(/^[1-9]$/.test(key)&&game.s.phase==='battle'){const c=game.s.battle.hand[Number(key)-1];if(c)handle('play',{dataset:{uid:c.uid}});}});
document.addEventListener('keydown',e=>{if(!modalName||e.key!=='Tab')return;const focusable=[...document.querySelectorAll('.modal button:not(:disabled),.modal input,.modal [tabindex="0"]')];if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
document.addEventListener('change',async e=>{if(e.target.id!=='import-save'||busy)return;const file=e.target.files[0];if(!file)return;if(file.size>500000){toast('저장 파일이 너무 큽니다.');return;}try{const raw=await file.text(),loaded=Game.load({getItem:()=>raw});if(!loaded)throw Error('invalid');game=new Game(loaded).init();tutorial=!game.s.introSeen;afterMutation();toast('원정을 불러왔습니다.');}catch{toast('유효한 월영 저장 파일을 선택해 주세요.');}});
render();if(game.s.phase!=='battle')phaseModal();
