import {background as fallbackBackground,heroSprite as fallbackHero,portrait as fallbackPortrait,cardArt as fallbackCard} from './art.js';
const urls={heroes:new URL('../assets/heroes.webp',import.meta.url),worlds:new URL('../assets/worlds.webp',import.meta.url),cards:new URL('../assets/cards.webp',import.meta.url),enemies:new URL('../assets/enemies.webp',import.meta.url)};
export const images={};
export async function loadAssets(){await Promise.all(Object.entries(urls).map(([key,url])=>new Promise(resolve=>{const im=new Image();im.onload=()=>{images[key]=im;resolve();};im.onerror=()=>resolve();im.src=url.href;})));}
const owners=['seol','lyra','aria'];
const cardOrder=['slash','guard','spark','ward','bash','protect','bond','moon','storm','lotus','heal','focus','nova','fortress','flash','frost'];
export const worldPosition=['0% 0%','100% 0%','0% 100%','100% 100%'];
function tile(ctx,image,column,row,columns,rows,x,y,w,h){const tw=image.width/columns,th=image.height/rows;ctx.drawImage(image,column*tw,row*th,tw,th,x,y,w,h);}
export function portrait(canvas,id){if(!images.heroes)return fallbackPortrait(canvas,id);canvas.width=100;canvas.height=100;const c=canvas.getContext('2d'),index=owners.indexOf(id),xs=[230,680,1210];c.fillStyle=['#123731','#342847','#443726'][index];c.fillRect(0,0,100,100);c.imageSmoothingEnabled=false;c.drawImage(images.heroes,xs[index],120,200,240,0,0,100,120);}
export function cardArt(canvas,icon,owner,id){if(!images.cards)return fallbackCard(canvas,icon,owner);canvas.width=384;canvas.height=256;const c=canvas.getContext('2d'),index=Math.max(0,cardOrder.indexOf(id));c.imageSmoothingEnabled=false;tile(c,images.cards,index%4,Math.floor(index/4),4,4,0,0,384,256);}
export class Scene{
 constructor(canvas,chapter,party,enemies){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.chapter=chapter;this.party=party;this.enemies=enemies;this.effects=[];this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.alive=true;this.frame=this.frame.bind(this);this.canvas.width=1440;this.canvas.height=Math.round(1440*canvas.getBoundingClientRect().height/canvas.getBoundingClientRect().width);this.bg=images.worlds?null:fallbackBackground(chapter);this.frame(performance.now());}
 stop(){this.alive=false;cancelAnimationFrame(this.raf);}
 burst(effect){this.effects.push({...effect,at:performance.now()});}
 targetPoint(uid){const r=this.canvas.getBoundingClientRect(),e=this.enemies.find(x=>x.uid===uid),i=this.enemies.indexOf(e);return{x:r.left+r.width*(this.enemies.length===1?.77:.65+i*.19),y:r.top+r.height*.64};}
 heroPoint(id){const r=this.canvas.getBoundingClientRect();return{x:r.left+r.width*([.135,.275,.415][owners.indexOf(id)]),y:r.top+r.height*.58};}
 frame(now){if(!this.alive)return;const c=this.ctx,w=this.canvas.width,h=this.canvas.height;c.clearRect(0,0,w,h);c.imageSmoothingEnabled=false;if(images.worlds)tile(c,images.worlds,this.chapter%2,Math.floor(this.chapter/2),2,2,0,0,w,h);else c.drawImage(this.bg,0,0,w,h);
 const shade=c.createLinearGradient(0,0,0,h);shade.addColorStop(0,'#070f2150');shade.addColorStop(.5,'#0d122110');shade.addColorStop(1,'#070f2190');c.fillStyle=shade;c.fillRect(0,0,w,h);
 const active=this.effects.filter(e=>now-e.at<800);this.effects=active;
 if(!this.reduced){for(let i=0;i<25;i++){const x=(i*179+now*.015)%w,y=30+(i*47)%360+Math.sin(now*.001+i)*9;c.globalAlpha=.3+.25*Math.sin(now*.002+i);c.fillStyle=this.chapter===3?'#efb6ff':'#b6e6d8';c.fillRect(x,y,2,2);}c.globalAlpha=1;}
 this.party.forEach((hero,i)=>{const x=w*[.135,.275,.415][i],attack=active.find(e=>e.owner===hero.id&&e.type==='attack'),hit=active.find(e=>e.type==='enemy'&&e.target===hero.id),dt=attack?now-attack.at:0,dx=attack&&!this.reduced?Math.sin(dt/800*Math.PI)*26:0,bob=this.reduced?0:Math.sin(now*.002+i)*1.5,hh=305*h/480,ww=hh*.502;c.save();c.globalAlpha=hero.hp>0?1:.25;this.shadow(x,h*.86,57);if(images.heroes)tile(c,images.heroes,i,0,3,1,x-ww/2+dx,h*.87-hh+bob,ww,hh);else c.drawImage(fallbackHero(hero.id),x-60,h*.87-174,120,174);
 if(hero.block>0){c.strokeStyle='#b2f4dc88';c.lineWidth=2;c.shadowColor='#7bf3c2';c.shadowBlur=15;c.beginPath();c.ellipse(x,h*.57,78,142,0,0,Math.PI*2);c.stroke();}if(hit&&now-hit.at<180){c.fillStyle='#ffd6b033';c.fillRect(x-65,130,130,250);}c.restore();});
 this.enemies.forEach((e,i)=>{const x=w*(this.enemies.length===1?.77:.65+i*.19),isBoss=['queen','demon'].includes(e.kind),hh=(isBoss?330:e.kind==='wolf'?220:265)*h/480,ww=(isBoss?250:e.kind==='wolf'?270:215)*h/480,hit=active.find(f=>f.type==='attack'&&f.target===e.uid),dt=hit?now-hit.at:0,dx=hit&&!this.reduced?Math.sin(dt*.09)*(1-dt/800)*9:0,bob=e.kind==='wisp'&&!this.reduced?Math.sin(now*.002)*8:0;c.save();c.globalAlpha=e.hp>0?1:hit?Math.max(.08,.7-dt/600):.08;this.shadow(x,h*.86,70);if(images.enemies){const index=e.id==='master'?4:e.kind==='wolf'?0:e.kind==='wisp'?1:e.kind==='knight'?2:e.kind==='queen'?3:5;tile(c,images.enemies,index%3,Math.floor(index/3),3,2,x-ww/2+dx,h*.87-hh+bob,ww,hh);if(hit&&dt<125){c.globalCompositeOperation='screen';c.globalAlpha=.65;tile(c,images.enemies,index%3,Math.floor(index/3),3,2,x-ww/2+dx,h*.87-hh+bob,ww,hh);}}
 else{c.fillStyle='#8c769d';c.beginPath();c.ellipse(x,h*.65,65,95,0,0,Math.PI*2);c.fill();}c.restore();});
 active.forEach(e=>this.paint(e,now));this.raf=requestAnimationFrame(this.frame);
 }
 shadow(x,y,size){const c=this.ctx;c.fillStyle='#07101b80';c.beginPath();c.ellipse(x,y,size,9,0,0,Math.PI*2);c.fill();}
 paint(e,now){const c=this.ctx,t=(now-e.at)/800;if(e.type==='attack'||e.type==='enemy'){const p=e.type==='enemy'?this.heroPoint(e.target):this.targetPoint(e.target),r=this.canvas.getBoundingClientRect(),x=(p.x-r.left)/r.width*this.canvas.width,y=(p.y-r.top)/r.height*this.canvas.height;c.save();c.globalAlpha=1-t;c.font=`bold ${e.combo?40:32}px Galmuri`;c.textAlign='center';c.lineWidth=5;c.strokeStyle='#11101e';const label=e.amount===0?'방어':String(e.amount);c.strokeText(label,x,y-55-t*55);c.fillStyle=e.type==='enemy'?'#ffb8a1':e.combo?'#ffe6a0':'#fff4dc';c.fillText(label,x,y-55-t*55);if(e.type==='enemy'){c.strokeStyle='#febd9b';c.lineWidth=5;c.beginPath();c.moveTo(x-45,y-35);c.lineTo(x+45,y+45);c.stroke();}c.restore();}}
}
